language: node_js
node_js:
  - "12.13.1"

git:
  depth: false

cache:
  yarn: true

before_install:
  - npm install -g firebase-tools

script:
  - yarn test
  - echo "yarn test finished"
  - yarn build
  - echo "TRAVIS_BUILD_DIR:"$TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR/packages/mapray
  - yarn pack
  - cd $TRAVIS_BUILD_DIR/packages/ui
  - yarn pack
  - cd $TRAVIS_BUILD_DIR

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh -t mapray -a dev
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh -t ui -a dev
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh -t mapray -a staging
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh -t ui -a staging
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh -t mapray -a production
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+(\.[0-9]+)
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh -t ui -a production
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+(\.[0-9]+)
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_cdn.sh ${FIREBASE_DEV_PROJECT} ${FIREBASE_DEPLOY_TOKEN}
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_cdn.sh ${FIREBASE_STG_PROJECT} ${FIREBASE_DEPLOY_TOKEN}
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_cdn.sh ${FIREBASE_PROD_PROJECT} ${FIREBASE_DEPLOY_TOKEN}
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+(\.[0-9]+)
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_npm_com.sh -t mapray -n ${NPM_TOKEN}
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+(\.[0-9]+)
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_npm_com.sh -t ui -n ${NPM_TOKEN}
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+(\.[0-9]+)
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_npm_com.sh -t mapray -n ${NPM_TOKEN} -d
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(?!master)
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_npm_com.sh -t ui -n ${NPM_TOKEN} -d
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(?!master)


