dist: bionic
language: node_js
node_js:
  - "12.13.1"

git:
  depth: false

cache:
  yarn: true

env:
  EMSDK=$HOME/emsdk

before_install:
  - git clone --branch=2.0.9 --depth=1 https://github.com/emscripten-core/emsdk.git $EMSDK

install:
  - npm install -g firebase-tools
  ## Install emscripten
  - cd $EMSDK
  - ./emsdk install latest
  - ./emsdk activate latest
  - git apply -p1 $TRAVIS_BUILD_DIR/packages/mapray/wasm/emsdk.patch

before_script:
  - source $EMSDK/emsdk_env.sh
  - cd $TRAVIS_BUILD_DIR
  - yarn install

script:
  - yarn test
  - echo "yarn test finished"
  - echo "TRAVIS_BUILD_DIR:"$TRAVIS_BUILD_DIR
  - bash $TRAVIS_BUILD_DIR/packages/mapray/wasm/rebuild_and_install.sh
  - yarn build
  - cd $TRAVIS_BUILD_DIR/packages/mapray
  - yarn pack
  - cd $TRAVIS_BUILD_DIR/packages/ui
  - yarn pack
  - cd $TRAVIS_BUILD_DIR

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh -t mapray -a dev
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh -t ui -a dev
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh -t mapray -a staging
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh -t ui -a staging
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh -t mapray -a production
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+(\.[0-9]+)
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh -t ui -a production
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+(\.[0-9]+)
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_cdn.sh ${FIREBASE_DEV_PROJECT} ${FIREBASE_DEPLOY_TOKEN}
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_cdn.sh ${FIREBASE_STG_PROJECT} ${FIREBASE_DEPLOY_TOKEN}
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_cdn.sh ${FIREBASE_PROD_PROJECT} ${FIREBASE_DEPLOY_TOKEN}
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+(\.[0-9]+)
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_npm_com.sh -t mapray -n ${NPM_TOKEN}
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+(\.[0-9]+)
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_npm_com.sh -t ui -n ${NPM_TOKEN}
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+(\.[0-9]+)
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_npm_com.sh -t mapray -n ${NPM_TOKEN} -d
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_npm_com.sh -t ui -n ${NPM_TOKEN} -d
    on:
      all_branches: true

