name: <CDN> Publish JS files
on:
  release:
    types: [released, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CORE_PACKAGE_DIR: "./packages/mapray"
      UI_PACKAGE_DIR: "./packages/ui"
      DEPLOY_DIR: "./_deploy"
      CORE_DEPLOY_DIR: "./_deploy/public/mapray-js"
      UI_DEPLOY_DIR: "./_deploy/public/ui"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run:  git fetch --prune --unshallow
      - name: Get deploy version
        run: |
          NEXT_VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo ${NEXT_VERSION}
          echo "::set-output name=next_version::${NEXT_VERSION}"
        id: get_version
        shell: bash
        working-directory: ${{ env.CORE_PACKAGE_DIR }}
      - name: Setup
        run: yarn install
      - name: Build maprayJS
        run: yarn build
      - name: Copy core built files to dist directory
        run: |
          mkdir -p ${{ env.CORE_DEPLOY_DIR }}/v${{ steps.get_version.outputs.next_version }}
          cp -r ${{ env.CORE_PACKAGE_DIR }}/dist/umd/* ${{ env.CORE_DEPLOY_DIR }}/v${{ steps.get_version.outputs.next_version }}
      - name: Copy ui built files to dist directory
        run: |
          mkdir -p ${{ env.UI_DEPLOY_DIR }}/v${{ steps.get_version.outputs.next_version }}
          mkdir -p ${{ env.DEPLOY_DIR }}/public/styles/v1
          cp -r ${{ env.UI_PACKAGE_DIR }}/dist/umd/* ${{ env.UI_DEPLOY_DIR }}/v${{ steps.get_version.outputs.next_version }}
          cp -r ${{ env.UI_PACKAGE_DIR }}/dist/mapray.css ${{ env.DEPLOY_DIR }}/public/styles/v1/
        shell: bash
      - name: Upload core files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ${{ env.CORE_DEPLOY_DIR }}
          destination: inou-pro-released/mapray-js
          credentials: ${{ secrets.STORE_CREDENTIALS }}
          parent: false
      - name: Upload ui files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ${{ env.UI_DEPLOY_DIR }}
          destination: inou-pro-released/ui
          credentials: ${{ secrets.STORE_CREDENTIALS }}
          parent: false
      - name: Upload style sheet
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ${{ env.DEPLOY_DIR }}/public/styles
          destination: inou-pro-released/styles
          credentials: ${{ secrets.STORE_CREDENTIALS }}
          parent: false
